### ISSUE TITLE
Problem with images

### ISSUE THREAD

**Issue by pallavid30** [multi-template-matching/MultiTemplateMatching-Python#18]
I am trying to use this for detecting cracks on metal surfaces. I am getting this error (copied in the end). I have attached the code and images to reproduce this error. Can you please help out?

Error:
________________

Traceback (most recent call last):
  File "/Users/pallavidubey/Documents/MultiTemplateMatching-Python/tutorials/SampleError.py", line 41, in <module>
    Hits = matchTemplates(listTemplate, im1, score_threshold=0.9, method=5, maxOverlap=0)
  File "/Users/pallavidubey/Documents/MultiTemplateMatching-Python/MTM/__init__.py", line 271, in matchTemplates
    tableHit = findMatches(listTemplates, image, method, N_object, score_threshold, searchBox)
  File "/Users/pallavidubey/Documents/MultiTemplateMatching-Python/MTM/__init__.py", line 149, in findMatches
    _ = future.result()
  File "/Users/pallavidubey/mambaforge/envs/mtm/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/pallavidubey/mambaforge/envs/mtm/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/pallavidubey/mambaforge/envs/mtm/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/pallavidubey/Documents/MultiTemplateMatching-Python/MTM/__init__.py", line 201, in _multi_compute
    corrMap = computeScoreMap(template, image, method, mask=mask)
  File "/Users/pallavidubey/Documents/MultiTemplateMatching-Python/MTM/__init__.py", line 87, in computeScoreMap
    return cv2.matchTemplate(image, template, method, mask=mask)
cv2.error: OpenCV(4.7.0) /Users/xperience/GHA-OCV-Python/_work/opencv-python/opencv-python/opencv/modules/imgproc/src/templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'crossCorr'
[SampleError.zip](https://github.com/multi-template-matching/MultiTemplateMatching-Python/files/11583156/SampleError.zip)

**Comment by LauLauThom** [comment]
Hi there,
The coordinates you give for slicing give templates of width and/or height 0.
Slicing in python is [start, stop] not [start, width] (for horizontal for instance) contrary to ex : imageJ.
But you could do [start, start+width-1] something like that.

I could add a check in the code to assert that the size of the images is >0 though.

**Comment by pallavid30** [comment]
Thank you, Laurent,

Silly mistake on my end. I will correct that and hopefully it should go smoothly from here, I will connect with you, if I get stuck someplace. I will be referencing your paper for my journal paper to benchmark my method against yours for defect detection.

Thank you,
With kind regards,


Pallavi Dubey (pronounced - Pul-Love-E, Do-Bay)

Ph.D. Candidate

Department of Industrial Manufacturing and Systems Engineering

Iowa State University

***@***.******@***.***>

________________________________
